 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: final-project-namespace-deployment
 spec:
   replicas: 1
   selector:
     matchLabels:
       app: finalprojectnamespace
   template:
     metadata:
       labels:
         app: finalprojectnamespace
     spec:
       containers:
       - name: finalprojectnamespace
         image: icr.io/final-project-namespace/finalapp
         imagePullPolicy: Always
         ports:
         - containerPort: 5000
